# Generated by Django 6.1.2 on 2026-10-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=2)),
                ('latitude', models.FloatField(db_index=True)),
                ('longitude', models.FloatField(db_index=True)),
                ('price', models.DecimalField(decimal_places=3, help_text='Retail price (USD/gallon)', max_digits=6)),
                ('truckstop_id', models.IntegerField(blank=True, null=True)),
                ('rack_id', models.IntegerField(blank=True, null=True)),
                ('is_approximate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['state', 'city', 'name'],
                'constraints': [models.UniqueConstraint(fields=('truckstop_id', 'address', 'city', 'state'), name='unique_station_per_truckstop_address')],
            },
        ),
    ]
